access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev

secret:
  key: tTPPmaP0J8jikt1VjHXEG7QQQmd7kwANFJf3xE92mbfkK9Ps3aY1Qdcm2gDvnbih
